# fly.toml app configuration file generated for jychin on 2023-11-15T20:34:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jychin"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  APP_URL="https://jychin.fly.dev"
  DB_CONNECTION="mysql"
  DB_HOST="aws.connect.psdb.cloud"
  DB_PORT="3306"
  DB_DATABASE="jychin"
  MYSQL_ATTR_SSL_CA="/etc/ssl/certs/ca-certificates.crt"
  REDIS_HOST= "off-redis.internal"
  CACHE_DRIVER= "redis"
  QUEUE_CONNECTION= "redis"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
